spring:
  payments:
    phonepe:
      merchantId: PGTESTPAYUAT
      saltKey: 099eb0cd-02cf-4e2a-8aca-3e6c6aff0399
      saltIndex: 1
      env: UAT
      shouldPublishEvents: true
      callbackUrl: http://localhost:8080/pay-return-url